"""
markdown_renderer.py
─────────────────────
Generates clean, GitHub-compatible Markdown reports from ReportData.
Two variants: Technical (full column tables) and Executive (business summary).
"""
from __future__ import annotations

from app.core.reports.data_compiler import ReportData

SAAR_VERSION = "1.0"


def _frontmatter(d: ReportData, report_type_label: str) -> str:
    return (
        "---\n"
        f"title: \"SAAR {report_type_label} — {d.filename}\"\n"
        f"generated_at: \"{d.generated_at}\"\n"
        f"dataset: \"{d.filename}\"\n"
        f"rows: {d.rows}\n"
        f"columns: {d.columns}\n"
        f"quality_score: {d.quality_score}\n"
        f"saar_version: \"{d.saar_version}\"\n"
        f"report_type: \"{d.report_type}\"\n"
        "analysis_engine: \"Python Statistical Engine\"\n"
        "---\n\n"
    )


def _footer(d: ReportData) -> str:
    return (
        "\n\n---\n\n"
        f"*Generated by SAAR v{d.saar_version} — Python Statistical Engine — AI Explanation Layer*  \n"
        f"*{d.generated_at_display}*  \n"
        f"*All statistical values are produced by the Python Statistical Engine. "
        f"AI was used only to improve natural language clarity.*\n"
    )


def render_technical(d: ReportData) -> str:
    md = []
    md.append(_frontmatter(d, "Technical Analysis Report"))
    md.append(f"# SAAR — Technical Analysis Report\n")
    md.append(f"**Dataset:** `{d.filename}`  ")
    md.append(f"**Generated:** {d.generated_at_display}  ")
    md.append(f"**SAAR Version:** v{d.saar_version}  ")
    md.append(f"**Report Type:** Technical\n")

    md.append("---\n")

    # Table of contents
    md.append("## Table of Contents\n")
    sections = [
        "1. Dataset Overview",
        "2. Data Quality Assessment",
        "3. Cleaning Summary",
        "4. Column Profile Registry",
        "5. Descriptive Statistics",
        "6. Key Findings & Insights",
        "7. Business Risks & Opportunities",
        "8. Hypothesis Tests",
        "9. Modelling Recommendations",
        "10. Methodology",
        "11. Final Summary",
    ]
    for s in sections:
        anchor = s.lower().replace(" ", "-").replace(".", "").replace("&", "").replace("/", "").replace("__", "_")
        md.append(f"- [{s}](#{anchor})")
    md.append("\n---\n")

    # 1. Overview
    md.append("## 1. Dataset Overview\n")
    md.append(f"| Metric | Value |")
    md.append(f"|---|---|")
    md.append(f"| Total Records | {d.rows:,} |")
    md.append(f"| Total Columns | {d.columns} |")
    md.append(f"| Missing Cells | {d.missing_total:,} |")
    md.append(f"| Duplicate Rows | {d.duplicates:,} |")
    md.append(f"| File Format | {d.file_format.upper()} |")
    md.append(f"| Quality Score | {d.quality_score}/100 |\n")
    md.append(f"> **Executive Summary:** {d.executive_summary}\n")

    if d.has_statistical_limitations:
        md.append("### Statistical Limitations\n")
        md.append(f"{d.reliability_explanation}\n")
        md.append("Because of the limited sample size:\n")
        for w in d.reliability_warnings:
            md.append(f"- {w}")
        md.append("")
        if d.reliability_actions:
            md.append("**Recommended Actions:**")
            for action in d.reliability_actions:
                md.append(f"- {action}")
            md.append("")

    # 2. Quality
    md.append("## 2. Data Quality Assessment\n")
    md.append(f"**Score:** {d.quality_score}/100 — {d.quality_explanation}\n")
    md.append("**Quality Observations:**\n")
    for r in d.quality_reasons:
        md.append(f"- {r}")
    md.append("")

    # 3. Cleaning
    md.append("## 3. Cleaning Summary\n")
    if d.cleaning_history:
        for i, h in enumerate(d.cleaning_history, 1):
            md.append(f"**Pipeline #{i} — {h.get('timestamp','')}**\n")
            md.append("| Operation | Column | Strategy |")
            md.append("|---|---|---|")
            for op in h.get("operations", []):
                op_type = op.get("type", "").replace("_", " ").title()
                col = op.get("column", "—")
                strat = op.get("strategy", "—")
                md.append(f"| {op_type} | {col} | {strat} |")
            md.append("")
    else:
        md.append("No cleaning operations have been applied.\n")

    # 4. Column profiles
    md.append("## 4. Column Profile Registry\n")
    md.append("| Column | Semantic Type | Dtype | Missing | Unique | Statistics | Outliers |")
    md.append("|---|---|---|---|---|---|---|")
    for p in d.column_profiles:
        out = f"{p.outlier_count} ({p.outlier_pct}%)" if p.semantic_type == "numeric" else "N/A"
        stats = p.stats_summary[:80]
        md.append(f"| `{p.name}` | {p.semantic_type} | `{p.pandas_type}` | {p.null_count} ({p.null_pct}%) | {p.unique_count} | {stats} | {out} |")
    md.append("")

    # 5. Descriptive stats
    md.append("## 5. Descriptive Statistics\n")
    num_profiles = [p for p in d.column_profiles if p.semantic_type == "numeric"]
    if num_profiles:
        md.append("| Column | Statistics | Outliers | Missing |")
        md.append("|---|---|---|---|")
        for p in num_profiles:
            md.append(f"| `{p.name}` | {p.stats_summary[:80]} | {p.outlier_count} ({p.outlier_pct}%) | {p.null_count} ({p.null_pct}%) |")
    else:
        md.append("No numeric columns found.")
    md.append("")

    # 6. Findings
    md.append("## 6. Key Findings & Insights\n")
    for i, f in enumerate(d.key_findings, 1):
        md.append(f"{i}. {f}")
    md.append("")

    # 7. Risks & opportunities
    md.append("## 7. Business Risks & Opportunities\n")
    md.append("### Business Risks\n")
    for r in d.risks:
        md.append(f"- ⚠️ {r}")
    md.append("\n### Opportunities\n")
    for o in d.opportunities:
        md.append(f"- 💡 {o}")
    md.append("")

    # 8. Hypothesis tests
    md.append("## 8. Hypothesis Tests\n")
    if d.hypothesis_tests:
        md.append("| Test Name | Type | Variables | Statistic | P-Value | Result | Interpretation |")
        md.append("|---|---|---|---|---|---|---|")
        for t in d.hypothesis_tests:
            stat = f"{t.statistic:.4f}" if t.statistic is not None else "N/A"
            pval = f"{t.p_value:.4f}" if t.p_value is not None else "N/A"
            sig = "✅ Significant" if t.significant else "— Not Significant"
            md.append(f"| {t.test_name} | {t.test_type} | {', '.join(t.variables)} | {stat} | {pval} | {sig} | {t.interpretation} |")
    else:
        md.append("No hypothesis tests were performed on this dataset.")
    md.append("")

    # 9. Modelling
    md.append("## 9. Modelling Recommendations\n")
    if not d.can_model:
        action_str = ", ".join(d.reliability_actions)
        md.append(f"Modeling is not recommended due to limited sample size: {d.reliability_explanation} Recommended actions: {action_str}\n")
    else:
        if d.potential_targets:
            for t in d.potential_targets:
                md.append(f"- **Target:** `{t['column']}` — {t.get('task','')} | Models: {', '.join(t.get('suggested_models',[]))}")
                if t.get("reasoning"):
                    md.append(f"  > {t['reasoning']}")
        elif d.unsupervised_recs:
            for u in d.unsupervised_recs:
                md.append(f"- **{u.get('task','')}** — {u.get('reasoning','')}")
                md.append(f"  > Recommended: {', '.join(u.get('suggested_models',[]))}")
        else:
            md.append("No modelling recommendations available.")
    md.append("")

    # 10. Methodology
    md.append("## 10. Methodology\n")
    md.append(f"*{d.methodology}*\n")

    # 11. Final summary
    md.append("## 11. Final Summary\n")
    status = "Ready for Analysis" if d.quality_score >= 80 else "Needs Cleaning" if d.quality_score >= 60 else "Requires Significant Cleaning"
    md.append("| Metric | Value |")
    md.append("|---|---|")
    md.append(f"| Data Quality Score | {d.quality_score}/100 |")
    md.append(f"| Quality Observations | {len(d.quality_reasons)} |")
    md.append(f"| Key Findings | {len(d.key_findings)} |")
    md.append(f"| Risks Identified | {len(d.risks)} |")
    md.append(f"| Opportunities | {len(d.opportunities)} |")
    md.append(f"| Analysis Status | {status} |")

    md.append(_footer(d))
    return "\n".join(md)


def render_executive(d: ReportData) -> str:
    md = []
    md.append(_frontmatter(d, "Executive Summary Report"))
    md.append(f"# SAAR — Executive Summary Report\n")
    md.append(f"**Dataset:** `{d.filename}`  ")
    md.append(f"**Generated:** {d.generated_at_display}  ")
    md.append(f"**SAAR Version:** v{d.saar_version}\n")
    md.append("---\n")

    md.append("## 1. Executive Overview\n")
    md.append(f"> {d.executive_summary}\n")
    md.append(f"| Metric | Value |")
    md.append(f"|---|---|")
    md.append(f"| Quality Score | {d.quality_score}/100 |")
    md.append(f"| Total Records | {d.rows:,} |")
    md.append(f"| Data Columns | {d.columns} |")
    md.append("")

    if d.has_statistical_limitations:
        md.append("### Statistical Limitations\n")
        md.append(f"{d.reliability_explanation}\n")
        md.append("Because of the limited sample size:\n")
        for w in d.reliability_warnings:
            md.append(f"- {w}")
        md.append("")
        if d.reliability_actions:
            md.append("**Recommended Actions:**")
            for action in d.reliability_actions:
                md.append(f"- {action}")
            md.append("")

    md.append("## 2. Dataset Health\n")
    status = "Excellent" if d.quality_score >= 80 else "Requires Attention" if d.quality_score >= 60 else "Needs Cleaning"
    md.append(f"**{d.quality_score}/100 — {status}**  ")
    md.append(f"{d.quality_explanation}\n")
    for r in d.quality_reasons[:5]:
        md.append(f"- ⚠️ {r}")
    md.append("")

    md.append("## 3. Key Insights\n")
    for i, f in enumerate(d.key_findings, 1):
        md.append(f"{i}. {f}")
    md.append("")

    md.append("## 4. Business Risks & Opportunities\n")
    md.append("### Risks\n")
    for r in d.risks:
        md.append(f"- ⚠️ {r}")
    md.append("\n### Opportunities\n")
    for o in d.opportunities:
        md.append(f"- 💡 {o}")
    md.append("")

    md.append("## 5. Recommendations\n")
    if not d.can_model:
        action_str = ", ".join(d.reliability_actions)
        md.append(f"Modeling is not recommended due to limited sample size: {d.reliability_explanation} Recommended actions: {action_str}\n")
    else:
        if d.potential_targets:
            for t in d.potential_targets:
                md.append(f"- **`{t['column']}`** is a strong candidate for {t.get('task','')} modelling ({', '.join(t.get('suggested_models',[]))}).")
        elif d.unsupervised_recs:
            for u in d.unsupervised_recs:
                md.append(f"- **{u.get('task','')}:** {u.get('reasoning','')}")
        else:
            md.append("- Continue with data cleaning before selecting a modelling approach.")
    md.append("")

    md.append("## 6. Methodology\n")
    md.append(f"*{d.methodology}*\n")

    md.append("## 7. Final Summary\n")
    status2 = "Ready for Analysis" if d.quality_score >= 80 else "Needs Cleaning" if d.quality_score >= 60 else "Requires Significant Cleaning"
    md.append("| Metric | Value |")
    md.append("|---|---|")
    md.append(f"| Data Quality Score | {d.quality_score}/100 |")
    md.append(f"| Key Findings | {len(d.key_findings)} |")
    md.append(f"| Risks Identified | {len(d.risks)} |")
    md.append(f"| Analysis Status | {status2} |")

    md.append(_footer(d))
    return "\n".join(md)
