import json
from typing import Dict, Any

# ── Preamble ─────────────────────────────────────────────────────────────────
PREAMBLE = """You are a Senior Data Analyst explaining verified statistical analysis produced by SAAR's Python Statistical Engine.

ABSOLUTE RULES — you must never violate these:
1. You are explaining already-computed verified facts. You are NOT performing analysis.
2. Never calculate statistics. Never invent numbers. Never modify supplied values.
3. Never hallucinate. Never fabricate findings that are not in the supplied data.
4. If evidence is insufficient to draw a conclusion, explicitly say so.
5. Mention uncertainty where appropriate.
6. Never infer causation from correlation unless statistical evidence explicitly supports it.
   - INCORRECT: "Wealth caused higher survival."
   - CORRECT: "A strong association exists between passenger class and survival, but this analysis alone cannot establish causation."
7. Reference only the supplied JSON payload. Do not use any outside knowledge to invent new numbers or conclusions.
8. Your output must be valid JSON only — no prose wrappers, no markdown fences, no ```json tags."""

# ── JSON schema template string ───────────────────────────────────────────────
JSON_SCHEMA = """{
  "title": "<concise title for this explanation>",
  "summary": "<main explanation — see word limit below>",
  "key_takeaway": "<one or two actionable sentences — the single most important conclusion>",
  "evidence": [
    {"label": "<metric name>", "value": "<exact value from payload>", "source": "Python Statistical Engine"}
  ],
  "limitations": "<caveats, assumptions, or uncertainty notes — or 'None' if not applicable>",
  "provider": ""
}"""

FOOTER_NOTE = (
    "This explanation is based entirely on verified statistical analysis generated by "
    "SAAR's Python Statistical Engine. AI was used only to improve clarity and readability."
)

# ── Level instructions ────────────────────────────────────────────────────────
def get_level_instruction(level: str) -> str:
    level = level.lower().strip()
    if level == "beginner":
        return (
            "Explain in simple, everyday language. Use intuitive analogies. "
            "Avoid statistical jargon entirely. Keep the summary under 100 words."
        )
    elif level == "expert":
        return (
            "Explain using formal statistical and data science terminology. "
            "Discuss modeling consequences, mathematical assumptions, and implications. "
            "Keep the summary under 300 words."
        )
    else:  # intermediate
        return (
            "Explain using clear, professional business language. Balance technical accuracy "
            "with readability. Avoid overly academic jargon. Keep the summary under 180 words."
        )


# ── Prompt builders ───────────────────────────────────────────────────────────

def build_recommendation_prompt(payload: Dict[str, Any], level: str) -> str:
    level_instruction = get_level_instruction(level)
    return f"""{PREAMBLE}

Explanation Level: {level.upper()}
Instruction: {level_instruction}

Verified data cleaning recommendation payload:
{json.dumps(payload, indent=2)}

Your explanation must cover these topics within the summary:
- WHY: Why does this issue exist and why does it matter?
- MISSING PERCENTAGE (if applicable): Explain the specific percentage in context.
- IMPACT: What positive impact will executing this recommendation have?
- MODELING CONSEQUENCES: How does this issue affect future modeling or ML?
- ALTERNATIVE APPROACHES: What other approaches could a data scientist use?

The key_takeaway must be one actionable sentence recommending the best course of action.

In the evidence array, include all numeric values from the payload (missing percentages, counts, severity, etc.).

Respond with ONLY this JSON structure — no prose, no code fences:
{JSON_SCHEMA}
"""


def build_chart_prompt(payload: Dict[str, Any], level: str) -> str:
    level_instruction = get_level_instruction(level)
    # Strip large data arrays — only send chart metadata, not raw data points
    chart_info = {
        "type": payload.get("type"),
        "title": payload.get("title"),
        "x_axis": payload.get("x_axis"),
        "y_axis": payload.get("y_axis"),
        "description": payload.get("description"),
        "data_sample": (payload.get("data", []) or [])[:8],
    }
    return f"""{PREAMBLE}

Explanation Level: {level.upper()}
Instruction: {level_instruction}

Verified chart metadata (no raw dataset sent — only metadata and a data sample):
{json.dumps(chart_info, indent=2)}

Your explanation must cover:
- CHART REPRESENTATION: What this chart type represents based on the axes.
- KEY PATTERNS: What the user should look for — distributions, trends, or relationships visible in the sample.
- PRACTICAL SIGNIFICANCE: What this chart reveals analytically.

Do NOT invent patterns not visible in the supplied data sample.

The key_takeaway must state the single most analytically meaningful observation.

In the evidence array, list the chart type, x-axis, y-axis, and description as evidence items.

Respond with ONLY this JSON structure — no prose, no code fences:
{JSON_SCHEMA}
"""


def build_test_prompt(payload: Dict[str, Any], level: str) -> str:
    level_instruction = get_level_instruction(level)
    p_val = payload.get("p_value", "N/A")
    stat = payload.get("statistic", "N/A")
    significant = payload.get("significant", False)
    return f"""{PREAMBLE}

Explanation Level: {level.upper()}
Instruction: {level_instruction}

Verified statistical test result:
{json.dumps(payload, indent=2)}

Your explanation must cover:
- TEST DESCRIPTION: What test was used and why it was appropriate for these variables.
- NULL HYPOTHESIS: State the null hypothesis clearly.
- P-VALUE & SIGNIFICANCE: Explain p-value = {p_val} and whether it is significant (alpha = 0.05).
  Result: {"Significant — reject null hypothesis" if significant else "Not significant — fail to reject null hypothesis"}.
- PRACTICAL IMPLICATION: Business or analytical consequence of this result.

IMPORTANT: Do not infer causation. Describe statistical associations only.
The key_takeaway must summarise what the result means in one actionable sentence.

In the evidence array, include: test_type, statistic={stat}, p_value={p_val}, significant={significant}.

Respond with ONLY this JSON structure — no prose, no code fences:
{JSON_SCHEMA}
"""


def build_summary_prompt(payload: Dict[str, Any], level: str) -> str:
    level_instruction = get_level_instruction(level)
    return f"""{PREAMBLE}

Explanation Level: {level.upper()}
Instruction: {level_instruction}

Verified dataset quality and EDA metadata:
{json.dumps(payload, indent=2)}

Your explanation must cover:
- EXECUTIVE SUMMARY: High-level narrative: record count, features, and key anomalies.
- BUSINESS INSIGHTS: Translate statistical findings into business-ready language.
- NEXT STEPS: Suggest concrete next actions (cleaning, modeling directions).

Do NOT invent any numbers. Use ONLY the values provided in the payload.
The key_takeaway must state the single most important action the user should take.

In the evidence array, include: total rows, missing values, duplicates, quality score if available.

Respond with ONLY this JSON structure — no prose, no code fences:
{JSON_SCHEMA}
"""


def build_quality_prompt(payload: Dict[str, Any], level: str) -> str:
    level_instruction = get_level_instruction(level)
    score = payload.get("score", "N/A")
    return f"""{PREAMBLE}

Explanation Level: {level.upper()}
Instruction: {level_instruction}

Verified Data Quality Score and observations:
{json.dumps(payload, indent=2)}

Your explanation must cover:
- SCORE EXPLANATION: What a score of {score}/100 means for this dataset.
- REASONS FOR DEDUCTION: Explain each reason why points were deducted using the exact reasons provided.
- HOW TO IMPROVE: Concrete, actionable steps to improve the score.

Use ONLY the exact score value {score} — do not alter or approximate it.
The key_takeaway must state the most impactful single action to improve data quality.

In the evidence array, include: score, and each reason as a separate evidence item.

Respond with ONLY this JSON structure — no prose, no code fences:
{JSON_SCHEMA}
"""


def build_insight_prompt(payload: Dict[str, Any], level: str) -> str:
    level_instruction = get_level_instruction(level)
    return f"""{PREAMBLE}

Explanation Level: {level.upper()}
Instruction: {level_instruction}

Verified analytical insight derived from the Python Statistical Engine:
{json.dumps(payload, indent=2)}

Your explanation must cover:
- WHY THIS INSIGHT EXISTS: What statistical pattern or finding produced this insight?
- STATISTICAL EVIDENCE: Which specific metrics or values in the payload support it?
- ASSUMPTIONS: What assumptions underlie this insight?
- PRACTICAL MEANING: What does this mean for the business, analysis, or modeling pipeline?

CRITICAL: Do NOT invent new findings. Do NOT infer causation from correlation.
If the payload does not contain sufficient evidence for a strong conclusion, explicitly state uncertainty.

The key_takeaway must summarise the practical meaning in one actionable sentence.
In the evidence array, list every numeric or categorical value from the payload.

Respond with ONLY this JSON structure — no prose, no code fences:
{JSON_SCHEMA}
"""


def build_report_prompt(payload: Dict[str, Any], level: str) -> str:
    level_instruction = get_level_instruction(level)
    return f"""{PREAMBLE}

Explanation Level: {level.upper()}
Instruction: {level_instruction}

Verified analytics report payload (executive summary, findings, risks, opportunities):
{json.dumps(payload, indent=2)}

Your task is to IMPROVE the narrative clarity, tone, and logical flow of this report.
Do NOT change, invent, or remove any statistical value.
Do NOT add new conclusions not present in the payload.

The key_takeaway must be a single sentence summarising the most important finding.
In the evidence array, list the core findings and risks as evidence items referencing the payload.

Respond with ONLY this JSON structure — no prose, no code fences:
{JSON_SCHEMA}
"""


def build_presentation_prompt(payload: Dict[str, Any], level: str) -> str:
    """
    Presentation Mode: Converts verified analysis into a business/stakeholder-friendly narrative.
    Does NOT generate new statistics. Only reorganises existing verified findings.
    Audience: managers, business stakeholders, clients.
    """
    return f"""{PREAMBLE}

TASK: Presentation Mode

Transform the following verified analytical findings into a concise, executive-level presentation narrative.

Target audience: Managers, business stakeholders, clients.
Tone: Concise, professional, business-focused, presentation-ready.
Sentence style: Short sentences. Active voice. Business language only. No statistical jargon.

Verified findings payload:
{json.dumps(payload, indent=2)}

STRICT REQUIREMENTS:
- Do NOT generate any new statistics, numbers, or conclusions.
- Do NOT introduce findings not present in the payload.
- Do NOT use academic or technical terminology.
- ONLY reorganise and present the existing verified findings in a clear, executive narrative.
- The summary should read like a professional slide deck narrative.

Structure the narrative as:
1. Situation: What does the data tell us?
2. Key Findings: The most critical verified findings (business-friendly).
3. Recommended Actions: Based ONLY on the existing recommendations in the payload.

The key_takeaway must be suitable for an executive summary slide.
In the evidence array, list 3–5 of the most impactful findings from the payload.

Respond with ONLY this JSON structure — no prose, no code fences:
{JSON_SCHEMA}
"""
