import re
from datetime import datetime, timezone
from typing import Dict, Any, List


class RuleBasedExplainer:
    """
    Deterministic rule-based explanation engine.
    Always returns a fully structured dict matching the AI response schema:
    {
        "title": str,
        "summary": str,
        "key_takeaway": str,
        "evidence": List[{"label", "value", "source"}],
        "limitations": str,
        "provider": str,
        "generated_at": str,
    }
    This guarantees structural consistency with LLM providers.
    """

    PROVIDER_NAME = "rule_based_fallback"
    FOOTER = (
        "This explanation is based entirely on verified statistical analysis generated by "
        "SAAR's Python Statistical Engine. AI was used only to improve clarity and readability."
    )

    @staticmethod
    def _make_response(
        title: str,
        summary: str,
        key_takeaway: str,
        evidence: List[Dict],
        limitations: str = "Rule-based explanations are deterministic templates. For richer analysis, configure a Gemini or OpenAI API key.",
    ) -> Dict[str, Any]:
        return {
            "title": title,
            "summary": summary,
            "key_takeaway": key_takeaway,
            "evidence": [
                {
                    "label": e.get("label", ""),
                    "value": str(e.get("value", "")),
                    "source": e.get("source", "Python Statistical Engine"),
                }
                for e in evidence
            ],
            "limitations": limitations,
            "provider": RuleBasedExplainer.PROVIDER_NAME,
            "generated_at": datetime.now(timezone.utc).isoformat(),
        }

    @staticmethod
    def explain(explanation_type: str, level: str, payload: Dict[str, Any]) -> Dict[str, Any]:
        explanation_type = explanation_type.lower().strip()
        level = level.lower().strip()

        dispatch = {
            "recommendation": RuleBasedExplainer._explain_recommendation,
            "chart": RuleBasedExplainer._explain_chart,
            "statistical_test": RuleBasedExplainer._explain_test,
            "executive_summary": RuleBasedExplainer._explain_summary,
            "quality_score": RuleBasedExplainer._explain_quality,
            "report": RuleBasedExplainer._explain_report,
            "presentation": RuleBasedExplainer._explain_presentation,
            "insight": RuleBasedExplainer._explain_insight,
        }
        fn = dispatch.get(explanation_type, RuleBasedExplainer._explain_insight)
        return fn(payload, level)

    # ── Recommendation ────────────────────────────────────────────────────────

    @staticmethod
    def _explain_recommendation(payload: Dict[str, Any], level: str) -> Dict[str, Any]:
        rec_type = payload.get("type", "cleanup")
        col = payload.get("column") or "selected column"
        issue = payload.get("issue", "A data anomaly was detected.")
        rec = payload.get("recommendation", "Apply cleanup.")
        severity = payload.get("severity", "medium")

        # Extract missing percentage from issue string if present
        null_pct = payload.get("null_percentage", "")
        if not null_pct:
            match = re.search(r"\((\d+\.?\d*)%\)", issue)
            if match:
                null_pct = match.group(1)

        evidence = [
            {"label": "Issue", "value": issue, "source": "Python Statistical Engine"},
            {"label": "Severity", "value": severity, "source": "Python Statistical Engine"},
            {"label": "Recommended Operation", "value": rec_type, "source": "Python Statistical Engine"},
        ]
        if null_pct:
            evidence.append({"label": "Missing Percentage", "value": f"{null_pct}%", "source": "Python Statistical Engine"})
        if col and col != "selected column":
            evidence.append({"label": "Affected Column", "value": col, "source": "Python Statistical Engine"})

        if level == "beginner":
            summary = (
                f"This recommendation suggests fixing the column '{col}' because it has issues: {issue}. "
                "In data analysis, missing or duplicated values can make charts and summaries inaccurate. "
                "Applying this fix will help ensure your results are reliable and easy to read. "
                "If you skip this fix, your analysis might be skewed or show misleading patterns."
            )
            key_takeaway = f"Apply the recommended fix to '{col}' to ensure your analysis results are accurate and reliable."
        elif level == "expert":
            summary = (
                f"Structural anomaly detected: '{issue}'. This violates assumptions of completeness and independence "
                f"in downstream modeling. The recommended operation ({rec_type}) restores data integrity by eliminating "
                "collinearity noise and empty-cell bias. Without this fix, regression coefficients may exhibit inflated "
                "variance, gradient descent may converge suboptimally, and parameter estimates will be biased. "
                "Alternatives include MICE imputation, KNN imputation, or using tree-based models that handle missingness natively."
            )
            key_takeaway = f"Apply {rec_type} on '{col}' before modeling to prevent biased parameter estimates and maintain statistical validity."
        else:
            summary = (
                f"This recommendation addresses: '{issue}'. Missing or duplicate data reduces the reliability of statistical "
                f"estimates and can introduce noise into aggregations. Executing '{rec}' will standardise the column, "
                "resulting in more reliable visualisations and downstream calculations. "
                "Alternative options include listwise deletion or custom default value assignments."
            )
            key_takeaway = f"Resolve the issue in '{col}' to improve the reliability of your analysis and predictive models."

        return RuleBasedExplainer._make_response(
            title=f"Why this recommendation? ({rec_type})",
            summary=summary,
            key_takeaway=key_takeaway,
            evidence=evidence,
        )

    # ── Chart ─────────────────────────────────────────────────────────────────

    @staticmethod
    def _explain_chart(payload: Dict[str, Any], level: str) -> Dict[str, Any]:
        chart_type = payload.get("type", "chart")
        title = payload.get("title", "Data Visualization")
        x_axis = payload.get("x_axis", "X-Axis")
        y_axis = payload.get("y_axis", "Y-Axis")
        desc = payload.get("description", "A visualization of the data.")

        evidence = [
            {"label": "Chart Type", "value": chart_type, "source": "Python Statistical Engine"},
            {"label": "X-Axis", "value": x_axis, "source": "Python Statistical Engine"},
            {"label": "Y-Axis", "value": y_axis, "source": "Python Statistical Engine"},
            {"label": "Description", "value": desc, "source": "Python Statistical Engine"},
        ]

        if level == "beginner":
            summary = (
                f"This is a {chart_type} chart called '{title}'. It shows the relationship between "
                f"'{x_axis}' (horizontal) and '{y_axis}' (vertical). Look for the tallest bars or "
                "densest clusters — those represent where most of your data lies. "
                f"{desc}"
            )
            key_takeaway = f"Look for peaks or clusters in this chart — they indicate where your '{y_axis}' values are most concentrated."
        elif level == "expert":
            summary = (
                f"This {chart_type} represents the {'bivariate' if x_axis != y_axis else 'univariate'} "
                f"distribution '{title}', mapping '{x_axis}' to '{y_axis}'. "
                "Examine the skewness, kurtosis, modal peaks, or linear/non-linear relationships. "
                "Outliers are visible outside the standard density boundaries. "
                f"{desc} This distribution enables evaluation of variance, homoscedasticity, and correlation "
                "coefficients — essential for validating statistical modeling assumptions."
            )
            key_takeaway = f"Analyse the distributional shape and outlier presence in '{x_axis}' vs '{y_axis}' before applying parametric models."
        else:
            summary = (
                f"This {chart_type} chart illustrates '{title}', showing the relationship between "
                f"'{x_axis}' and '{y_axis}'. Observe trends, clusters, or bin frequencies. "
                f"{desc} It provides a clear picture of feature distributions, which helps identify "
                "target segments or skewed data columns."
            )
            key_takeaway = f"Review the pattern between '{x_axis}' and '{y_axis}' to identify trends or anomalies before modelling."

        return RuleBasedExplainer._make_response(
            title=f"Explain Chart: {title}",
            summary=summary,
            key_takeaway=key_takeaway,
            evidence=evidence,
        )

    # ── Statistical Test ──────────────────────────────────────────────────────

    @staticmethod
    def _explain_test(payload: Dict[str, Any], level: str) -> Dict[str, Any]:
        test_type = payload.get("test_type", "Statistical Test")
        test_name = payload.get("test_name", "Hypothesis Test")
        variables = payload.get("variables", [])
        stat = payload.get("statistic", 0.0)
        p_val = payload.get("p_value", 1.0)
        sig = payload.get("significant", False)
        interpretation = payload.get("interpretation", "No interpretation provided.")

        var_text = " vs ".join(variables) if variables else "selected features"
        sig_word = "statistically significant" if sig else "not statistically significant"

        evidence = [
            {"label": "Test Type", "value": test_type, "source": "Python Statistical Engine"},
            {"label": "Variables", "value": var_text, "source": "Python Statistical Engine"},
            {"label": "Test Statistic", "value": f"{stat:.4f}" if isinstance(stat, float) else str(stat), "source": "Python Statistical Engine"},
            {"label": "P-Value", "value": f"{p_val:.4f}" if isinstance(p_val, float) else str(p_val), "source": "Python Statistical Engine"},
            {"label": "Significant", "value": "Yes (p < 0.05)" if sig else "No (p ≥ 0.05)", "source": "Python Statistical Engine"},
        ]

        if level == "beginner":
            summary = (
                f"A '{test_type}' called '{test_name}' was used to check if there is a real connection between {var_text}. "
                "The test starts with the assumption that there is no difference (the default state). "
                f"The p-value is {p_val:.4f}. Since this is {'less than 0.05' if sig else 'greater than 0.05'}, "
                f"the result is {'unlikely to be random luck' if sig else 'likely just random variation'}. "
                f"In simple terms: {interpretation}"
            )
            key_takeaway = f"The test result is {sig_word} — {interpretation}"
        elif level == "expert":
            summary = (
                f"The engine performed '{test_name}' on {var_text}. "
                f"Null Hypothesis (H₀): No statistical difference exists between {var_text}. "
                f"Test statistic = {stat:.4f}, p-value = {p_val:.4f}. "
                f"At α = 0.05, we {'reject' if sig else 'fail to reject'} H₀. "
                f"The result is {sig_word}. Note: statistical significance does not imply causation. "
                f"Modeling implication: {interpretation}"
            )
            key_takeaway = f"{'Reject H₀' if sig else 'Fail to reject H₀'} at α=0.05 (p={p_val:.4f}). {interpretation}"
        else:
            summary = (
                f"A '{test_type}' was performed to evaluate the relationship between {var_text}. "
                f"The test yielded a p-value of {p_val:.4f}. "
                f"A p-value {'below' if sig else 'above'} 0.05 indicates the result is {sig_word}. "
                f"Practical takeaway: {interpretation}"
            )
            key_takeaway = f"The result is {sig_word} (p={p_val:.4f}). {interpretation}"

        return RuleBasedExplainer._make_response(
            title=f"Explain Result: {test_type}",
            summary=summary,
            key_takeaway=key_takeaway,
            evidence=evidence,
        )

    # ── Executive Summary ─────────────────────────────────────────────────────

    @staticmethod
    def _explain_summary(payload: Dict[str, Any], level: str) -> Dict[str, Any]:
        quality = payload.get("quality_overview", payload.get("quality", {}))
        total_rows = quality.get("total_rows", 0)
        duplicates = quality.get("duplicate_rows", 0)
        missing_vals = quality.get("missing_values", {})
        total_missing = sum(missing_vals.values()) if isinstance(missing_vals, dict) else 0

        evidence = [
            {"label": "Total Rows", "value": str(total_rows), "source": "Python Statistical Engine"},
            {"label": "Total Missing Values", "value": str(total_missing), "source": "Python Statistical Engine"},
            {"label": "Duplicate Rows", "value": str(duplicates), "source": "Python Statistical Engine"},
        ]

        dup_rate = f"{(duplicates / total_rows * 100):.2f}%" if total_rows > 0 else "N/A"

        if level == "beginner":
            summary = (
                f"The dataset has {total_rows} rows in total. "
                f"We found {total_missing} missing values and {duplicates} duplicate rows. "
                "This gives a general view of how complete and clean your data is. "
                "Focus on columns with high missing numbers first. "
                "Duplicates should be cleaned to prevent double-counting."
            )
            key_takeaway = "Start by cleaning duplicate rows and columns with the most missing values before running any analysis."
        elif level == "expert":
            summary = (
                f"Dataset dimensions: N = {total_rows} observations. "
                f"The data profile contains {total_missing} missing values and a duplicate rate of {dup_rate} (count: {duplicates}). "
                "High collinearity or missingness rates dictate whether multiple imputation, dimensionality reduction, "
                "or feature extraction is appropriate prior to modeling."
            )
            key_takeaway = "Prioritise dimensionality assessment and imputation strategy before fitting any predictive model."
        else:
            summary = (
                f"This dataset consists of {total_rows} records. "
                f"Key statistics show {total_missing} missing data points and {duplicates} duplicate records. "
                "It is highly recommended to address missing values and duplicates to ensure statistical "
                "charts and downstream calculations are accurate."
            )
            key_takeaway = "Address missing values and duplicates in the Cleaning tab before proceeding with visualisations or modelling."

        return RuleBasedExplainer._make_response(
            title="Executive Dataset Summary",
            summary=summary,
            key_takeaway=key_takeaway,
            evidence=evidence,
        )

    # ── Quality Score ─────────────────────────────────────────────────────────

    @staticmethod
    def _explain_quality(payload: Dict[str, Any], level: str) -> Dict[str, Any]:
        score = payload.get("score", 100)
        reasons = payload.get("reasons", [])
        explanation = payload.get("explanation", "")

        evidence = [
            {"label": "Quality Score", "value": f"{score}/100", "source": "Python Statistical Engine"},
        ]
        for r in reasons:
            evidence.append({"label": "Deduction Reason", "value": str(r), "source": "Python Statistical Engine"})

        reasons_text = " ".join([f"- {r}" for r in reasons]) if reasons else "No specific deductions recorded."

        if level == "beginner":
            summary = (
                f"Your dataset scored {score}/100. {explanation} "
                "This score reflects how clean and complete your data is — like a health check for your data. "
                f"Reasons for deductions: {reasons_text} "
                "Apply the recommended fixes under the Cleaning tab to improve this score."
            )
            key_takeaway = f"Your data quality score is {score}/100. Apply the cleaning recommendations to improve it."
        elif level == "expert":
            summary = (
                f"Data Quality Score: {score}/100. This metric is computed using deductions for "
                "missingness, duplication, constant columns, and statistical outliers. "
                f"{explanation} Deduction sources: {reasons_text} "
                "Remediation: impute numerical columns using median/MICE, apply mode imputation for categoricals, "
                "and clip outliers beyond 1.5× IQR."
            )
            key_takeaway = f"Score of {score}/100 indicates {'severe' if score < 60 else 'moderate' if score < 80 else 'minor'} data quality issues. Prioritise high-impact deductions first."
        else:
            summary = (
                f"The dataset received a quality score of {score}/100. {explanation} "
                f"Points were deducted for the following issues: {reasons_text} "
                "Resolve duplicate records and impute missing data to increase the score."
            )
            key_takeaway = f"A score of {score}/100 means your dataset needs attention. Focus on the highest-severity issues first."

        return RuleBasedExplainer._make_response(
            title=f"Data Quality Score: {score}/100",
            summary=summary,
            key_takeaway=key_takeaway,
            evidence=evidence,
        )

    # ── Insight ───────────────────────────────────────────────────────────────

    @staticmethod
    def _explain_insight(payload: Dict[str, Any], level: str) -> Dict[str, Any]:
        insight_type = payload.get("type", "insight")
        insight_text = payload.get("insight", payload.get("text", payload.get("description", "Statistical relationship identified.")))
        category = payload.get("category", "General")

        evidence = []
        for k, v in payload.items():
            if k not in ("type", "insight", "text", "description", "category") and v is not None:
                if not isinstance(v, (dict, list)):
                    evidence.append({"label": k.replace("_", " ").title(), "value": str(v), "source": "Python Statistical Engine"})

        if level == "beginner":
            summary = (
                f"This insight ({category}) was identified from your data: {insight_text} "
                "This pattern was found by the Python Statistical Engine by analysing the relationships "
                "and values in your dataset. This insight can help guide decisions or highlight areas to investigate further."
            )
            key_takeaway = f"This finding suggests: {insight_text} Use it to guide your next analytical steps."
        elif level == "expert":
            summary = (
                f"Category: {category}. Analytical finding: {insight_text} "
                "This insight was derived from verified statistical computations. "
                "Statistical associations described here do not imply causation unless explicitly supported by experimental evidence. "
                "Treat this as a hypothesis to be validated with additional domain knowledge or confirmatory analysis."
            )
            key_takeaway = f"Validated statistical finding: {insight_text} Confirm with domain expertise before drawing causal conclusions."
        else:
            summary = (
                f"This {category} insight was identified: {insight_text} "
                "The Python Statistical Engine identified this pattern from the dataset's verified metrics. "
                "Use this finding to guide further investigation or inform business decisions. "
                "Note that statistical associations do not necessarily imply causation."
            )
            key_takeaway = f"Key finding: {insight_text} Investigate further to determine practical implications."

        return RuleBasedExplainer._make_response(
            title=f"Explain Insight: {category}",
            summary=summary,
            key_takeaway=key_takeaway,
            evidence=evidence if evidence else [{"label": "Insight", "value": insight_text, "source": "Python Statistical Engine"}],
            limitations="Statistical associations do not imply causation. Validate findings with domain knowledge.",
        )

    # ── Report ────────────────────────────────────────────────────────────────

    @staticmethod
    def _explain_report(payload: Dict[str, Any], level: str) -> Dict[str, Any]:
        filename = payload.get("filename", "dataset")
        exec_summary = payload.get("executive_summary", "")
        findings = payload.get("key_findings", [])

        evidence = [
            {"label": "Dataset", "value": filename, "source": "Python Statistical Engine"},
        ]
        for i, f in enumerate(findings[:5], 1):
            evidence.append({"label": f"Finding {i}", "value": str(f), "source": "Python Statistical Engine"})

        summary = (
            f"The statistical profile of '{filename}' has been analysed. "
            f"{exec_summary} "
            "Key features, relationships, and quality indexes have been evaluated. "
            "Use the findings to align analytical objectives and prioritise data preparation steps."
        )

        return RuleBasedExplainer._make_response(
            title=f"Analytics Report: {filename}",
            summary=summary,
            key_takeaway="Review the key findings and apply the cleaning recommendations to prepare this dataset for modelling or reporting.",
            evidence=evidence,
        )

    # ── Presentation Mode ─────────────────────────────────────────────────────

    @staticmethod
    def _explain_presentation(payload: Dict[str, Any], level: str) -> Dict[str, Any]:
        filename = payload.get("filename", "dataset")
        exec_summary = payload.get("executive_summary", "")
        findings = payload.get("key_findings", [])
        risks = payload.get("risks", [])
        opportunities = payload.get("opportunities", [])

        evidence = []
        for i, f in enumerate(findings[:3], 1):
            evidence.append({"label": f"Key Finding {i}", "value": str(f), "source": "Python Statistical Engine"})
        for i, r in enumerate(risks[:2], 1):
            evidence.append({"label": f"Risk {i}", "value": str(r), "source": "Python Statistical Engine"})
        for i, o in enumerate(opportunities[:2], 1):
            evidence.append({"label": f"Opportunity {i}", "value": str(o), "source": "Python Statistical Engine"})

        findings_text = " ".join([f"{i+1}. {f}" for i, f in enumerate(findings[:4])]) if findings else "See full report for details."
        risks_text = ", ".join([str(r) for r in risks[:3]]) if risks else "No critical risks identified."
        opps_text = ", ".join([str(o) for o in opportunities[:3]]) if opportunities else "See report for opportunities."

        summary = (
            f"SITUATION: Analysis of '{filename}' has been completed. {exec_summary} "
            f"\n\nKEY FINDINGS: {findings_text} "
            f"\n\nRISKS TO ADDRESS: {risks_text} "
            f"\n\nOPPORTUNITIES: {opps_text} "
            "\n\nAll findings are based on verified statistical analysis. No additional conclusions have been drawn."
        )

        key_takeaway = (
            f"The analysis of '{filename}' reveals actionable findings. "
            "Address the identified risks first, then leverage the opportunities for analytical and business value."
        )

        return RuleBasedExplainer._make_response(
            title=f"Executive Presentation: {filename}",
            summary=summary,
            key_takeaway=key_takeaway,
            evidence=evidence if evidence else [{"label": "Source", "value": filename, "source": "Python Statistical Engine"}],
            limitations="This presentation narrative is derived exclusively from verified statistical analysis. No new conclusions have been introduced.",
        )
